*** Variables ***


# ==============================
# FORMULÁRIO
# ==============================

${INPUT_NOME}             //input[@name='pessoa.nome']
${INPUT_EMAIL}            //input[@placeholder='email@exemplo.com']
${INPUT_TELEFONE}         //input[@placeholder='(11) 96123-4567']

${BTN_CONCLUIR}           //button[@id='rbBtnNext']

${MSG_BASE_LEGAL}         //li[normalize-space()='É necessário informar a base legal']